export enum DirectMessageEventEnum {
  DIRECT_MESSAGE = 'DIRECT_MESSAGE',
  JOIN_CONVERSATION = 'JOIN_CONVERSATION',
  DIRECT_MESSAGE_UPDATE = 'DIRECT_MESSAGE_UPDATE',
  DELETE_DIRECT_MESSAGE = 'DELETE_DIRECT_MESSAGE',
}

export enum ChannelMessageEventEnum {
  CHANNEL_MESSAGE = 'CHANNEL_MESSAGE',
  JOIN_CHANNEL = 'JOIN_CHANNEL',
  CHANNEL_MESSAGE_UPDATE = 'CHANNEL_MESSAGE_UPDATE',
  CHANNEL_MESSAGE_DELETE = 'CHANNEL_MESSAGE_DELETE',
}
